=== BoukeliaAbdelbasset/emploidutemps/trunk/XML/bdedt.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT bdedt (inspecteurs, enseignants, étudiants, groupes, matières, salles, edt)>

<!ELEMENT nom (#PCDATA)> 
<!ELEMENT prénom (#PCDATA)>
<!ELEMENT mél (#PCDATA)>
<!ELEMENT login (#PCDATA)> 
<!ELEMENT pass (#PCDATA)>

<!ELEMENT inspecteurs (inspecteur*)>

<!ELEMENT inspecteur (nom, prénom, mél, login, pass)>
<!ATTLIST inspecteur promotion CDATA #REQUIRED>
<!ATTLIST inspecteur id CDATA #REQUIRED>

<!ELEMENT enseignants (enseignant*)>

<!ELEMENT enseignant (nom, prénom, mél, login, pass)>
<!ATTLIST enseignant id CDATA #REQUIRED>

<!ELEMENT étudiants (promotion*)>

<!ELEMENT promotion (étudiant*)>
<!ATTLIST promotion id CDATA #REQUIRED>

<!ELEMENT étudiant (nom, prénom, login, pass)>
<!ATTLIST étudiant id CDATA #REQUIRED>

<!ELEMENT groupes (groupe*)>
<!ELEMENT groupe EMPTY>
<!ATTLIST groupe id CDATA #REQUIRED>
<!ATTLIST groupe étudiants CDATA #REQUIRED><!-- liste des id d'étudiants, séparés par un espace -->

<!ELEMENT matières (matière*)>

<!ELEMENT matière (intitulé, enseignements)>
<!ATTLIST matière id CDATA #REQUIRED>
<!ATTLIST matière type (facultatif|obligatoire) "obligatoire">
<!ELEMENT intitulé (#PCDATA)>

<!ELEMENT enseignements (CM?, TD?, TP?, BE?)>

<!ELEMENT CM EMPTY>
<!ATTLIST CM volume CDATA #REQUIRED><!-- format  hh:mm (hh=heures, mm=minutes) -->
<!ATTLIST CM enseignants CDATA #REQUIRED><!-- liste des id d'enseignant, séparés par un espace -->
<!ATTLIST CM groupes CDATA #REQUIRED><!-- liste des id de groupe, séparés par un espace -->
<!-- un enseignant aura le groupe correspondant à sa position dans la liste -->

<!ELEMENT TD EMPTY>
<!ATTLIST TD volume CDATA #REQUIRED><!-- format  hh:mm (hh=heures, mm=minutes) -->
<!ATTLIST TD enseignants CDATA #REQUIRED><!-- liste des id d'enseignant, séparés par un espace -->
<!ATTLIST TD groupes CDATA #REQUIRED><!-- liste des id de groupe, séparés par un espace -->
<!-- un enseignant aura le groupe correspondant à sa position dans la liste -->

<!ELEMENT TP EMPTY>
<!ATTLIST TP volume CDATA #REQUIRED><!-- format  hh:mm (hh=heures, mm=minutes) -->
<!ATTLIST TP enseignants CDATA #REQUIRED><!-- liste des id d'enseignant, séparés par un espace -->
<!ATTLIST TP groupes CDATA #REQUIRED><!-- liste des id de groupe, séparés par un espace -->
<!-- un enseignant aura le groupe correspondant à sa position dans la liste -->

<!ELEMENT BE EMPTY> 
<!ATTLIST BE volume CDATA #REQUIRED><!-- format  hh:mm (hh=heures, mm=minutes) -->
<!ATTLIST BE enseignants CDATA #REQUIRED><!-- liste des id d'enseignant, séparés par un espace -->
<!ATTLIST BE groupes CDATA #REQUIRED><!-- liste des id de groupe, séparés par un espace -->
<!-- un enseignant aura le groupe correspondant à sa position dans la liste -->

<!ELEMENT salles (salle*)>
<!ELEMENT salle EMPTY>
<!ATTLIST salle type (amphi|cours|tp) "cours">
<!ATTLIST salle taille CDATA #REQUIRED>
<!ATTLIST salle id CDATA #REQUIRED>

<!ELEMENT edt (réservation*)>
<!ELEMENT réservation EMPTY>
<!ATTLIST réservation date CDATA #REQUIRED><!-- format  jj/mm/aaaa (jj=jour, mm=mois, aaaa=année) -->
<!ATTLIST réservation heure CDATA #REQUIRED><!-- format  hh:mm (hh=heures, mm=minutes) -->
<!ATTLIST réservation durée CDATA #REQUIRED><!-- format  hh:mm (hh=heures, mm=minutes) -->
<!ATTLIST réservation salle CDATA #REQUIRED>
<!ATTLIST réservation groupe CDATA #REQUIRED>
<!ATTLIST réservation matière CDATA #REQUIRED>

=== BoukeliaAbdelbasset/emploidutemps/XML/bdedt2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bdedt SYSTEM "bdedt.dtd">
<bdedt>
	<inspecteurs>
	    <inspecteur id="1" promotion="4GI">
	      <nom>Remen</nom>
	      <prénom>Alexander</prénom>
	      <mél>alex.remen@gmail.com</mél>
	      <login>aremen</login>
	      <pass>toto1</pass>
	    </inspecteur>
	    <inspecteur id="2" promotion="4RT">
	      <nom>Vo Thanh</nom>
	      <prénom>Tonya</prénom>
	      <mél>sadako22@free.fr</mél>
	      <login>tvo_than</login>
	      <pass>toto2</pass>
	    </inspecteur>
		<inspecteur id="3" promotion="4GM">
			<nom>inspect3</nom>
			<prénom>toto3</prénom>
			<mél>toto3@bla</mél>
			<login>toto3</login>
			<pass>toto3</pass>
		</inspecteur>
	</inspecteurs>
	<enseignants>
		<enseignant id="1">
			<nom>enseign1</nom>
			<prénom>titi1</prénom>
			<mél>titi1@bla</mél>
			<login>titi1</login>
			<pass>titi1</pass>
		</enseignant>
		<enseignant id="2">
			<nom>enseign2</nom>
			<prénom>titi2</prénom>
			<mél>titi2@bla</mél>
			<login>titi2</login>
			<pass>titi2</pass>
		</enseignant>
		<enseignant id="3">
			<nom>enseign3</nom>
			<prénom>titi3</prénom>
			<mél>titi3@bla</mél>
			<login>titi3</login>
			<pass>titi3</pass>
		</enseignant>
	</enseignants>
	<étudiants>
		<promotion id="4GI">
				<étudiant id="1">
					<nom>etud1</nom>
					<prénom>lala1</prénom>
					<login>lala1</login>
					<pass>lala1</pass>
				</étudiant>
				<étudiant id="2">
					<nom>etud2</nom>
					<prénom>lala2</prénom>
					<login>lala2</login>
					<pass>lala2</pass>
				</étudiant>
		</promotion>
		<promotion id="4RT">
				<étudiant id="3">
					<nom>etud3</nom>
					<prénom>lala3</prénom>
					<login>lala3</login>
					<pass>lala3</pass>
				</étudiant>
				<étudiant id="4">
					<nom>etud4</nom>
					<prénom>lala4</prénom>
					<login>lala4</login>
					<pass>lala4</pass>
				</étudiant>
		</promotion>
		<promotion id="4GM">
				<étudiant id="5">
					<nom>etud5</nom>
					<prénom>lala5</prénom>
					<login>lala5</login>
					<pass>lala5</pass>
				</étudiant>
				<étudiant id="6">
					<nom>etud6</nom>
					<prénom>lala6</prénom>
					<login>lala6</login>
					<pass>lala6</pass>
				</étudiant>
		</promotion>
	</étudiants>
	<groupes>
		<groupe id="1" étudiants="1 2"/>
		<groupe id="11" étudiants="1"/>
		<groupe id="12" étudiants="2"/>
		<groupe id="2" étudiants="3 4"/>
		<groupe id="21" étudiants="3"/>
		<groupe id="22" étudiants="4"/>
		<groupe id="3" étudiants="5 6"/>
		<groupe id="31" étudiants="5"/>
		<groupe id="32" étudiants="6"/>
	</groupes>
	<matières>
		<matière id="1" type="obligatoire">
			<intitulé>mat1</intitulé>
			<enseignements>
				<CM enseignants="1 2 " groupes="1 2" volume="5:00"/>
				<TD enseignants="3" groupes="3" volume="10:00"/>
			</enseignements>
		</matière>
		<matière id="2" type="facultatif">
			<intitulé>mat2</intitulé>
			<enseignements>
				<CM enseignants="1 2" groupes="1 2" volume="5:00"/>
				<TD enseignants="3" groupes="3" volume="10:00"/>
			</enseignements>
		</matière>
		<matière id="3" type="obligatoire">
			<intitulé>mat3</intitulé>
			<enseignements>
				<CM enseignants="1 2 " groupes="1 2" volume="5:00"/>
				<TD enseignants="3" groupes="3" volume="10:00"/>
			</enseignements>
		</matière>
	</matières>
	<salles>
		<salle taille="15" id="1" type="amphi"/>
		<salle taille="15" id="2" type="cours"/>
		<salle taille="15" id="3" type="cours"/>
		<salle taille="15" id="4" type="tp"/>
	</salles>
	<edt>
		<réservation date="22/10/2007" salle="1" heure="8:00" durée="1:15" groupe="1" matière="1"/>
		<réservation date="22/11/2007" salle="2" heure="8:00" durée="1:15" groupe="2" matière="2"/>
		<réservation date="22/12/2007" salle="3" heure="8:00" durée="1:15" groupe="3" matière="3"/>
		<réservation date="07/01/2007" salle="3" heure="8:00" durée="1:15" groupe="3" matière="3"/>
	</edt>
</bdedt>

=== BoukeliaAbdelbasset/emploidutemps/trunk/XML/bdedt.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE bdedt SYSTEM 'bdedt.dtd'>

<bdedt>
 <inspecteurs>
  <inspecteur promotion="2006-GI-4" id="i1">
   <nom>Blanche</nom><prénom>Neige</prénom><mél>BlancheNeige@insa-tlse.fr</mél><login>i1</login><pass>i1</pass></inspecteur>
  <inspecteur promotion="2006-GI-5" id="i2">
   <nom>Prince</nom><prénom>Charmant</prénom><mél>PrinceCharmant@insa-tlse.fr</mél><login>i2</login><pass>i2</pass></inspecteur>
 </inspecteurs>
 <enseignants>
  <enseignant id="e1">
   <nom>Simplet</nom><prénom>simp</prénom><mél>simplet@insa-tlse.fr</mél>
   <login>simplet</login><pass>simp</pass>
  </enseignant>
  <enseignant id="e2">
   <nom>Dormeur</nom><prénom>dodo</prénom><mél>dormeur@insa-tlse.fr</mél>
   <login>dormeur</login><pass>dodo</pass>
  </enseignant>
  <enseignant id="e3">
   <nom>Grincheux</nom><prénom>grgr</prénom><mél>grincheux@insa-tlse.fr</mél>
  <login>grincheux</login><pass>grgr</pass>
  </enseignant>
  <enseignant id="e4">
   <nom>Prof</nom><prénom>pro</prénom><mél>prof@insa-tlse.fr</mél>
  <login>prof</login><pass>pro</pass>
  </enseignant>
  <enseignant id="e5">
   <nom>Atchoum</nom><prénom>souhait</prénom><mél>atchoum@insa-tlse.fr</mél>
  <login>atchoum</login><pass>souhait</pass>
  </enseignant>
  <enseignant id="e6">
   <nom>Joyeux</nom><prénom>joie</prénom><mél>joyeux@insa-tlse.fr</mél>
  <login>joyeux</login><pass>joie</pass>
  </enseignant>
  <enseignant id="e7">
   <nom>Timide</nom><prénom>euh</prénom><mél>timide@insa-tlse.fr</mél>
  <login>timide</login><pass>euh</pass>
  </enseignant>
 </enseignants>
 <étudiants>
  <promotion id="2006-GI-4">
   <étudiant id="e41"><nom>Nom étudiant 41</nom><prénom>pr 41 GI-4</prénom><login>e41</login><pass>e41</pass></étudiant>
   <étudiant id="e42"><nom>Nom étudiant 42</nom><prénom>pr 42 GI-4</prénom><login>e42</login><pass>e42</pass></étudiant>
   <étudiant id="e43"><nom>Nom étudiant 43</nom><prénom>pr 43 GI-4</prénom><login>e43</login><pass>e43</pass></étudiant>
   <étudiant id="e44"><nom>Nom étudiant 44</nom><prénom>pr 44 GI-4</prénom><login>e44</login><pass>e44</pass></étudiant>
   <étudiant id="e45"><nom>Nom étudiant 45</nom><prénom>pr 45 GI-4</prénom><login>e45</login><pass>e45</pass></étudiant>
   <étudiant id="e46"><nom>Nom étudiant 46</nom><prénom>pr 46 GI-4</prénom><login>e46</login><pass>e46</pass></étudiant>
   <étudiant id="e47"><nom>Nom étudiant 47</nom><prénom>pr 47 GI-4</prénom><login>e47</login><pass>e47</pass></étudiant>
   <étudiant id="e48"><nom>Nom étudiant 48</nom><prénom>pr 48 GI-4</prénom><login>e48</login><pass>e48</pass></étudiant>
  </promotion>
  <promotion id="2006-GI-5">
   <étudiant id="e51"><nom>Nom étudiant 51</nom><prénom>pr 51 GI-5</prénom><login>e51</login><pass>e51</pass></étudiant>
   <étudiant id="e52"><nom>Nom étudiant 52</nom><prénom>pr 52 GI-5</prénom><login>e52</login><pass>e52</pass></étudiant>
   <étudiant id="e53"><nom>Nom étudiant 53</nom><prénom>pr 53 GI-5</prénom><login>e53</login><pass>e53</pass></étudiant>
   <étudiant id="e54"><nom>Nom étudiant 54</nom><prénom>pr 54 GI-5</prénom><login>e54</login><pass>e54</pass></étudiant>
   <étudiant id="e55"><nom>Nom étudiant 55</nom><prénom>pr 55 GI-5</prénom><login>e55</login><pass>e55</pass></étudiant>
   <étudiant id="e56"><nom>Nom étudiant 56</nom><prénom>pr 56 GI-5</prénom><login>e56</login><pass>e56</pass></étudiant>
   <étudiant id="e57"><nom>Nom étudiant 57</nom><prénom>pr 57 GI-5</prénom><login>e57</login><pass>e57</pass></étudiant>
   <étudiant id="e58"><nom>Nom étudiant 58</nom><prénom>pr 58 GI-5</prénom><login>e58</login><pass>e58</pass></étudiant>
   <étudiant id="e59"><nom>Nom étudiant 59</nom><prénom>pr 59 GI-5</prénom><login>e59</login><pass>e59</pass></étudiant>
   <étudiant id="e60"><nom>Nom étudiant 60</nom><prénom>pr 60 GI-5</prénom><login>e60</login><pass>e60</pass></étudiant>
   <étudiant id="e61"><nom>Nom étudiant 61</nom><prénom>pr 61 GI-5</prénom><login>e61</login><pass>e61</pass></étudiant>
   <étudiant id="e62"><nom>Nom étudiant 62</nom><prénom>pr 62 GI-5</prénom><login>e62</login><pass>e62</pass></étudiant>
   <étudiant id="e63"><nom>Nom étudiant 63</nom><prénom>pr 63 GI-5</prénom><login>e63</login><pass>e63</pass></étudiant>
   <étudiant id="e64"><nom>Nom étudiant 64</nom><prénom>pr 64 GI-5</prénom><login>e64</login><pass>e64</pass></étudiant>
  </promotion>
 </étudiants>
 <groupes>
  <groupe id="40" étudiants="e41 e42 e43 e44 e45 e46 e47 e48"/>
  <groupe id="41" étudiants="e41 e42 e43 e44"/>
  <groupe id="42" étudiants="e45 e46 e47 e48"/>
  <groupe id="43" étudiants="e41 e42"/>
  <groupe id="44" étudiants="e43 e44"/>
  <groupe id="45" étudiants="e45 e46"/>
  <groupe id="46" étudiants="e47 e48"/>
  <groupe id="50" étudiants="e51 e52 e53 e54 e55 e56 e57 e58"/>
  <groupe id="51" étudiants="e51 e52 e53 e54"/>
  <groupe id="52" étudiants="e55 e56 e57 e58"/>
  <groupe id="53" étudiants="e51 e52"/>
  <groupe id="54" étudiants="e53 e54"/>
  <groupe id="55" étudiants="e55 e56"/>
  <groupe id="56" étudiants="e57 e58"/>
  <groupe id="57" étudiants="e59 e60"/>
  <groupe id="58" étudiants="e61 e62"/>
  <groupe id="59" étudiants="e63 e64"/>
 </groupes>
 <matières>
  <matière id="me4-1" type="obligatoire">
   <intitulé>Electronique 4e GI 1</intitulé>
   <enseignements>
    <CM volume="8:00" enseignants="e1" groupes="40"/>
    <TD volume="4:00" enseignants="e2 e3" groupes="41 42"/>
    <TP volume="4:00" enseignants="e4 e5 e6 e7" groupes="43 43 45 46"/>
   </enseignements>
  </matière>
  <matière id="me4-2" type="obligatoire">
   <intitulé>Electronique 4e GI 2</intitulé>
   <enseignements>
    <BE volume="4:00" enseignants="e4 e5 e6 e7" groupes="43 43 45 46"/>
   </enseignements>
  </matière>
  <matière id="me5-1">
   <intitulé>Informatique 5e GI</intitulé>
   <enseignements>
    <CM volume="8:00" enseignants="e1" groupes="50"/>
    <TD volume="4:00" enseignants="e2 e3" groupes="51 52"/>
    <TP volume="4:00" enseignants="e4 e5 e6" groupes="53 54 55"/>
    <BE volume="4:00" enseignants="e7 e8 e9 e10" groupes="56 57 58 59"/>
   </enseignements>
  </matière>
 </matières>
 <salles>
  <salle type="amphi" taille="100" id="Fourier"/>
  <salle type="amphi" taille="100" id="Vinci"/>
  <salle type="amphi" taille="100" id="Riquet"/>
  <salle type="cours" taille="80" id="STPI-109"/>
  <salle type="cours" taille="80" id="STPI-110"/>
  <salle type="cours" taille="80" id="STPI-111"/>
  <salle type="tp" taille="24" id="GEI-107"/>
  <salle type="tp" taille="24" id="GEI-108"/>
  <salle type="tp" taille="24" id="GEI-109"/>
  <salle type="tp" taille="24" id="GEI-110"/>
 </salles>
 <edt>
  <réservation date="27/10/2006" heure="8:00" durée="1:15" salle="Fourier" groupe="40" matière="me4-1"/>
  <réservation date="27/10/2006" heure="8:00" durée="2:45" salle="GEI-107" groupe="56" matière="me5-1"/>
  <réservation date="27/10/2006" heure="8:00" durée="2:45" salle="GEI-108" groupe="55" matière="me5-1"/>
 </edt>
</bdedt>

=== BoukeliaAbdelbasset/emploidutemps/XML/bdedtApi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bdedt SYSTEM "bdedt.dtd">

<bdedt>
  <inspecteurs>
    <inspecteur id="i1" promotion="2006-GI-4">
      <nom>Blanche</nom>
      <prénom>Neige</prénom>
      <mél>BlancheNeige@insa-tlse.fr</mél>
      <login>blanche</login>
      <pass>neige</pass>
    </inspecteur>
    <inspecteur id="i1" promotion="2006-GI-4">
      <nom>Blanche</nom>
      <prénom>Neige</prénom>
      <mél>BlancheNeige@insa-tlse.fr</mél>
      <login>blanche</login>
      <pass>neige</pass>
    </inspecteur>
  </inspecteurs>
  <enseignants />
  <étudiants>
    <promotion id="2006-GI-4" />
    <promotion id="2006-GI-4" />
  </étudiants>
  <groupes />
  <matières />
  <salles>
    <salle id="GEI-110" taille="24" type="tp" />
    <salle id="GEI-110" taille="24" type="tp" />
  </salles>
  <edt />
</bdedt>
